config:
  # plugins:
  #   metrics-by-endpoint: {}
  target: http://localhost:3000
  phases:
    - duration: 5
      arrivalRate: 50
scenarios:
  - name: Agregar y listar usuario
    flow:
      - get:
          url: "/usuario"
          capture:
            - json: $.nombre
              as: nombre
      - log: Creamos un usuario
      - post:
          url: /endpoint1
          json:
            name: "{{nombre}}"
          capture:
            - json: $.id
              as: userId
      - get:
          url: "/endpoint2/{{ userId }}"
          capture:
            - json: $.nombre
              as: userName
      - log: Listamos el usuario con id {{ userId }}, nombre {{userName}}
