config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 2
scenarios:
  - name: "Sessions Flow (registro + login)"
    flow:
      - log: "Creamos las variables para el usuario de prueba"
      - get:
          url: "/usuario"
          capture:
            - json: "$.nombre"
              as: "nombre"
            - json: "$.apellido"
              as: "apellido"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: "Registro de usuario"
      - post:
          url: "/registro"
          json:
            nombre: "{{nombre}}"
            apellido: "{{apellido}}"
            email: "{{email}}"
            password: "{{password}}"
      - think: 2
      - log: "Login"
      - post:
          url: "/login"
          json:
            email: "{{email}}"
            password: "{{password}}"
